### ISSUE TITLE
Errors after every reboot.

### ISSUE THREAD

**Issue by hansstulp** [bbqkees/ems-esp-domoticz-plugin#14]
After a reboot i get some error messages in the logfile:

2020-04-24 20:12:10.107 Error: (CV-ketel) 'onMessage' failed 'NameError'.
2020-04-24 20:12:10.107 Error: (CV-ketel) ----> Line 821 in '/home/pi/domoticz/plugins/ems-esp-domoticz-plugin/plugin.py', function onMessage
2020-04-24 20:12:10.107 Error: (CV-ketel) ----> Line 760 in '/home/pi/domoticz/plugins/ems-esp-domoticz-plugin/plugin.py', function onMessage
2020-04-24 20:12:10.108 Error: (CV-ketel) ----> Line 113 in '/home/pi/domoticz/plugins/ems-esp-domoticz-plugin/mqtt.py', function onMessage
2020-04-24 20:12:10.108 Error: (CV-ketel) ----> Line 792 in '/home/pi/domoticz/plugins/ems-esp-domoticz-plugin/plugin.py', function onMQTTPublish

I use 2020.1 on a Pi3 and updated all software.
How can i fix this?

Best regards
Hans

**Comment by FireWizard52** [comment]
Hell Hans,

Several reports of this problem exists here.
I had the same problem. See https://github.com/bbqkees/ems-esp-domoticz-plugin/issues/12

This problem was probably caused by a slow response of my MQTT server. My MQTT server was running on a Raspberry Pi 1B (1st generation) together with Node Red and Domoticz (slave).
I installed a new MQTT server in a FreeNAS (FreeBSD) jail and routed my EMS-ESP via this new and much faster MQTT server to my Raspberry Pi 2B (master). I have never seen this messages again after that I have moved to a faster MQTT server.
I believe the error messages are reported, because the data is not yet available, when needed.

If you have some faster hardware, you can try it yourself.

Best regards

**Comment by hansstulp** [comment]
That's not the reason. After an update i get the errors. Maybe a new install? Are there other solutions?

**Comment by bbqkees** [comment]
Its an error meaning something is called that is not there at that time. It only occurs once after a restart and it does not affect Domoticz at all. 
Its on my todo list.

**Comment by FireWizard52** [comment]
Some other users report the same problem, as you can see in the "closed" issue.

In your first post you mentioned that the errors are produced after a reboot, but in your last post you mention that it happens after an update. Update of what? Domoticz? EMS-ESP?
Both are followed by a new start.
I still believe that, as bbqkees also says, the data is not available at that moment. It is, in my opinion, confirmed by the fact that the error disappears as soon as I moved to another MQTT server (Mosquitto), running on faster hardware. But it does not effect the proper functioning of Domoticz.

**Comment by bbqkees** [comment]
The plugin is reloaded at boot or f.i. after an update of Domoticz or an update of the plugin itself so thats when you get the error.

**Comment by hansstulp** [comment]
Thanks for your reactions. I will close this issue.
