### ISSUE TITLE
EMS-ESP 2.0 - doesn`t work

### ISSUE THREAD

**Issue by sq4bja** [bbqkees/ems-esp-domoticz-plugin#16]
After upgrating EMS-ESP to new 2.0 version, plugin doesn`t work. Only Setpoint temperature is getting from MQTT.

**Comment by bbqkees** [comment]
Make sure nested json is on. Here it works fine with 2.0.

**Comment by sq4bja** [comment]
Ok, thanks. I`ll test it. Is it not nesssesary  to update devices, if i`m upgrading from 1.9.5?

**Comment by bbqkees** [comment]
For 2.0 you need to clear the Wemos before uploading the firmware because
the memory is dealt with differently.
But from the Domoticz side you don't need to change anything.
A good option is to test with MQTT explorer so you can see what the topic
structure is.
It needs to match 1.9.5 but it could be different in a fresh 2.0 so you
might need some additional config.

**Comment by sq4bja** [comment]
Ok, i have problem with EMS-rail - EMS-ESP can`t connect, so MQTT doesn`t work... Close.

**Comment by bbqkees** [comment]
You might need to change the tx-mode.
But this is all related to the bèta version of Ems-esp and not the Domoticz
plugin so it's beter to ask the questions on that repository.
