### ISSUE TITLE
MQTT thermostat topic changed

### ISSUE THREAD

**Issue by bobzomer** [bbqkees/ems-esp-domoticz-plugin#2]
With latest EMS-ESP (v1.9.2b3), the topic from my thermostat is now home/ems-esp/thermostat_data1 instead of home/ems-esp/thermostat_data.

Changing the topic subscription manually in the plugin solves the problem (but I guess it makes it specific to my setup).

**Comment by bbqkees** [comment]
Yes indeed lots of topics have changed.
Because there is now support for multiple heating circuits in the firmware, you need to instruct which heating circuit you want to set the temperature for.
In your case you only have one heating circuit so its always 1.
I'm going to update the plugin soon with support for all heating circuits.

**Comment by lmdecroos** [comment]
Any idea when we can expect the first beta for new the MQTT thermostat_data format?
I'm willing to test early versions and help troubleshooting.

**Comment by bbqkees** [comment]
@bobzomer I pulled your fix for hc1 into the main repo. I'm working on a solution for all 4 hc, together with a heartbeat, solar/mixer modules and Dallas sensors.

**Comment by bbqkees** [comment]
In the dev branch there is now a new update.

**Comment by lmdecroos** [comment]
just tested development version 0.7b12 with EMS-ESP gateway 1.9.3 and it’s working as expected for my HC1 and HC2

many thanks bbqkees
